algoritmo "CAIXA"
// Função :CAIXA
// Autor : Lucas Braga Lima
// Data : 15/09/2025
// Seção de Declarações 
var
produto:vetor [1..3] de caracter
indice: inteiro

inicio
// Seção de Comandos 

para indice de 1 ate 3 faca

escreval("Coloque as seguintes informações Nome, quantidade, valor")
leia(produto[indice])

fimpara
para indice de 1 ate 3 faca

escreval("Conferencia de dados",indice,":",produto[indice])
fimpara

escreval("CADASTRO CONSTUIDO COM SUCESSO")


fimalgoritmo
